OCR/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from ocr_app import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from ocr_app import views

urlpatterns = [
    url('admin/', admin.site.urls),
    path('', views.Index.as_view(), name='index'),
    path('home', views.Home.as_view(), name='home'),
    path('ocr/', include('ocr_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),


    # path('reset/', include('django.contrib.auth.urls'))
    # url('reset/', include('django.contrib.auth.urls')),
    # path('accounts/ password_change/', auth_views.PasswordResetForm, name='password_reset')
    # url(r'^accounts/password_reset/$', auth_views.PasswordResetView, name='password_reset'),
    # url(r'^accounts/password_reset/done/$', auth_views.PasswordChangeDoneView, name='password_reset_done'),
    # url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
    #     auth_views.PasswordResetConfirmView, name='password_reset_confirm'),
    # url(r'^accounts/reset/done/$', auth_views.PasswordResetCompleteView, name='password_reset_complete'),

]

ocr_app/urls.py
from django.urls import path
from django.views.static import serve

from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url


app_name = 'ocr_app'

urlpatterns = [
    path('register/', views.registration, name='register'),
    path('login/', views.login_user, name='login'),
    # Changed for trying purpose path('login/', views.login, name='login'),
    path('upload/<int:pk>', views.UploadImage, name='upload'),
    # path('config/<int:pk>', views.FileConfigurationForm, name='fileConfig'),
    path('process/<int:pk>', views.ImageProcess, name='process'),
    path('logout', views.logout_user, name='logout'),
    path('list/', views.listFiles, name='list'),
    path('history/<int:pk>', views.history, name='logs'),
    path('file/<str:fileName>/', views.fileDownload, name="fileDownload"),
    path('allfile/', views.allFiles, name='allFile'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/FileConfig.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
 {% if register %}
        <h1>Details are submitted...</h1>
        <a class="btn btn-primary" href="{% url 'ocr_app:process' user.id %}">Start</a>
    {% else %}
         <h3>Submit Details</h3>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    {% endif %}
</div>
{% endblock %}

templates/allFiles.html
{% extends "base.html" %}
{% load mytags %}
{% block body_block %}
<div class="jumbotron">
    {% if success %}
    <table class="table">
        <thead>
             <tr>
                <th>Image Name</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
     {% for val in value %}
            <tr>
                <td>{{ val|basename }}</td>
                <td><a href="/ocr/file/{{ val|basename }}/" target="_blank" class="btn btn-primary">Download</a></td>
            </tr>
     {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h2>Currently there is no file</h2>
    {% endif %}
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container">
             <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">Index</a></li>
                 <li><a class="navbar-brand" href="{% url 'ocr_app:register' %}">Registration</a></li>
                 {% if user.is_authenticated %}
                    <li><a class="navbar-brand" href="{% url 'ocr_app:logout' %}">logout</a></li>
                 {% else %}
                    <li><a class="navbar-brand" href="{% url 'ocr_app:login' %}">Login</a></li>
                 {% endif %}
            </ul>
       </div>
    </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

templates/complete.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
    {% if success %}
        <a href="{% url 'ocr_app:list' %}">Click here to Download</a>
    {% else %}
        <h2>Error</h2>
    {% endif %}
</div>
{% endblock %}

templates/demo.html
<!DOCTYPE html>
<html lang="en">
<body>
<a href="{% url 'ocr_app:download' %}" target="_blank">Download</a>
</body>
</html>

templates/files_list.html
{% extends "base.html" %}
{% load mytags %}
{% block body_block %}
<div class="jumbotron">
<table>
   <tr>
     <th>Image Name</td>
     <th>Download</td>
   </tr>
 {% for file in total_files %}
   <tr>
     <td>{{file}}</td>
     <td><a href="{{file.url}}">Download</a></td>
   </tr>
 {% endfor %}
</table>
</div>
{% endblock %}

templates/history.html
{% extends "base.html" %}
{% load mytags %}
{% block body_block %}
<div class="jumbotron">
    {% if success %}
    <table class="table">
        <thead>
             <tr>
                <th>Image Name</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
        {% for file,date in mylist %}
            <tr>
                    <td>{{ file }}</td>
                    <td>{{ date|date:'D, d M, Y' }}</td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    {% else %}
        <h3> No files </h3>
    {% endif %}

</div>
{% endblock %}

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">-->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<!--        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>-->
        <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<!--navbar navbar-expand-md navbar-dark bg-dark-->
 <nav class="navbar navbar-inverse  ">
     <ul class="nav navbar-nav">
         <li><a style="color:white" class="navbar-brand" href="{% url 'index' %}">Index</a></li>
        <li><a style="color:white" class="navbar-brand" href="{% url 'ocr_app:register' %}">Registration</a></li>
        {% if user.is_authenticated %}
            <li><a style="color:white" class="navbar-brand" href="{% url 'ocr_app:logout' %}">logout</a></li>
         {% else %}
            <li><a style="color:white" class="navbar-brand" href="{% url 'ocr_app:login' %}">Login</a></li>
         {% endif %}
     </ul>

     <ul class="nav navbar-nav navbar-right">
          <li><a style="color:white" href="#" class="navbar-brand" >Save</a></li>
          <li><a style="color:white" href="#" class="navbar-brand">Edit</a></li>
          <li><a style="color:white" href="#" class="navbar-brand">Save</a></li>
          <li><a style="color:white" href="#" class="navbar-brand">Edit</a></li>
      </ul>
<!--         <ul class="nav navbar-nav">-->
<!--                     <li><a href="#" class="navbar-brand navbar-right">Apple</a></li>-->
<!--         </ul>-->
    </nav>

  <div class="row">
    <div class="col-xs-9 col-md-7">
        <div class="container-fluid jumbotron">
          <div class="text-right">
                <p class="text-left">
                    <b>File Name : <br>Desription : <br>Size : </b>
                </p>
            </div>
<!--        <embed src="media/sample2.pdf" type="application/pdf"   height="650px" width="100%">-->
            <iframe src="media/sample2.pdf" height="650px" width="100%"></iframe>

    </div>
  </div>

    <div class="col-xs-3 col-md-5">
        <div class="text-right jumbotron">
            <br><br><br><br><br>
<!--            <embed src="media/sample2.pdf" type="application/pdf"   height="650px" width="100%">-->
            <iframe src="media/sample2.pdf" height="650px" width="100%"></iframe>

        </div>
    </div>
  </div>
 <div class="container">
        <ul class="pagination" >
            <li class="page-item"><a class="page-link" href="#">Previous</a></li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item"><a class="page-link" href="#">Next</a></li>
        </ul>
 </div>
</body>
</html>
<!--<iframe src="/home/shivani/PycharmProjects/OCR/OCR/templates/demo.pdf" style="width:718px; height:400px;" frameborder="2"></iframe>-->
<!--Worked-->
<!--<iframe src="https://docs.google.com/gview?url=https:///home/shivani/PycharmProjects/OCR/OCR/templates/demo.pdf&embedded=true" style="width:800px; height:500px;" frameborder="0"></iframe>-->

templates/index.html
{% extends "base.html" %}
{% block body_block %}
    <div class="jumbotron">
            {% if user.is_authenticated %}
                <h2>welcome {{ user.username }}</h2>
                <a class="btn btn-primary" href="{% url 'ocr_app:upload' user.id %}">Submit Image</a> <br> <br>
                <a class="btn btn-primary" href="{% url 'ocr_app:logs' user.id %}">History</a> <br> <br>
            {% else %}
                <h2>Register/Login to use service</h2>
            {% endif %}
    </div>
{% endblock %}

templates/listFile.html
{% extends "base.html" %}
{% load mytags %}
{% block body_block %}
<div class="jumbotron">
    <table class="table">
        <thead>
             <tr>
                <th>Image Name</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
        {% for val in value %}
            <tr>
                <td>{{ val|basename }}</td>
                <td><a href="" target="_blank">Download</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/upload.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block body_block %}
    <div class="jumbotron">
    {% if upload %}
        <h1>Details are submitted...</h1>
        <a class="btn btn-primary" href="{% url 'ocr_app:process' user.id %}">Start</a>

    {% else %}
        <h2>Upload here..</h2>
         <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
            {{ upload_form|crispy }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
    {% endif %}
    </div>
{% endblock %}